CC=gcc
CFLAGS=-I. -Wall -g
LIBS=-luser32 -lGdi32 -lKernel32

program: win32_main.o game.o
	$(CC) -o pugcombat win32_main.o game.o $(CFLAGS) $(LIBS)

win32_main.o: win32_main.c game.h
	$(CC) -c win32_main.c $(CFLAGS)

game.o: game.c game.h sprite.c
	$(CC) -c game.c $(CFLAGS)

clean:
	rm -f *.exe *.o

